function G_vec = G_func(in1,in2)
%G_func
%    G_vec = G_func(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-06-13 14:14:58

L = in1(3,:);
T_tension_val = in2(6,:);
g = in2(5,:);
m = in2(3,:);
qx1 = in1(6,:);
qx2 = in1(7,:);
qx3 = in1(8,:);
qy1 = in1(9,:);
qy2 = in1(10,:);
qy3 = in1(11,:);
rho = in2(4,:);
theta_x = in1(4,:);
theta_y = in1(5,:);
t2 = cos(theta_x);
t3 = cos(theta_y);
t4 = L.*rho;
t5 = pi.^2;
t6 = m.*2.0;
t7 = 1.0./L;
t8 = t4+t6;
G_vec = [0.0;0.0;-g.*m.*t2.*t3-g.*t2.*t3.*t4-(T_tension_val.*t5.*t7.^2.*(qx1.^2+qx2.^2.*4.0+qx3.^2.*9.0+qy1.^2+qy2.^2.*4.0+qy3.^2.*9.0))./4.0;(L.*g.*t3.*t8.*sin(theta_x))./2.0;(L.*g.*t2.*t8.*sin(theta_y))./2.0;(T_tension_val.*qx1.*t5.*t7)./2.0;T_tension_val.*qx2.*t5.*t7.*2.0;T_tension_val.*qx3.*t5.*t7.*(9.0./2.0);(T_tension_val.*qy1.*t5.*t7)./2.0;T_tension_val.*qy2.*t5.*t7.*2.0;T_tension_val.*qy3.*t5.*t7.*(9.0./2.0)];
end
